name: Create Release Package

on:
  release:
    types: [created]

jobs:
  build:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Extension Package
        run: |
          zip -r extension.zip . \
          -x "*.git*" \
          -x "*.github*" \
          -x "README.md" \
          -x "PRIVACY.md" \
          -x "LICENSE" \
          -x "*.DS_Store"

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./extension.zip
          asset_name: extension.zip
          asset_content_type: application/zip